[toolchain]
# Фиксируем актуальную стабильную версию компилятора
channel = "1.97.1"

# Базовый профиль установки (без лишней документации, только бинарники)
profile = "minimal"

# Дополнительные инструменты, необходимые для IDE (VS Code / Rust Rover) и CI/CD
components = [
    "rustfmt",         # Автоматическое форматирование кода
    "clippy",          # Продвинутый линтер для поиска ошибок и оптимизации
    "rust-analyzer"    # Языковой сервер для подсветки и автодополнения кода
]
